{% set name = "cosmosis-standalone" %}
{% set version = "0.2.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bcca317de0489abb9355b189ab5e0f1690fd3c9df9d3ba419707c845067932d8
  patches:
    - setup.py-env-0000.patch
    - datablock-makefile-0001.patch
    - runtime-makefile-0002.patch

build:
  number: 5
  skip: true  # [win]
  ignore_run_exports:
    - python

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  host:
    - python
    - pip
    - {{ mpi }}
    - liblapack
    - minuit2_standalone
  run:
    - python
    - {{ mpi }}
    - pyyaml
    - future
    - configparser
    - emcee
    - numpy
    - scipy
    - mpi4py
    - minuit2_standalone
    - git

test:
  requires:
    - pytest
  source_files:
    - test
  imports:
    - cosmosis
    - cosmosis.samplers
  commands:
    - test -f ${SP_DIR}/cosmosis/samplers/multinest/multinest_src/libnest3.so
    - test -f ${SP_DIR}/cosmosis/samplers/multinest/multinest_src/libnest3_mpi.so
    - test -f ${SP_DIR}/cosmosis/samplers/polychord/polychord_src/libchord.so
    - test -f ${SP_DIR}/cosmosis/samplers/polychord/polychord_src/libchord_mpi.so
    - pushd test
    - ${PYTHON} test_samplers.py test_multinest
    - popd

about:
  home: https://bitbucket.org/joezuntz/cosmosis/src/master/
  license: BSD-2-Clause AND LicenseRef-non-commerical-use-only
  license_file:
    - LICENSE
    - multinest_LICENSE
    - polychord_LICENSE
  summary: A stand-alone installation of the CosmoSIS project.

extra:
  recipe-maintainers:
    - beckermr
